openapi: 3.0.0
info:
  title: Argent Bank Transactions API
  description: API for managing transactions at Argent Bank.
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
    description: Development server
paths:
  /transactions:
    get:
      summary: Get all transactions for the current month
      description: Returns a list of transactions grouped by account for the current month.
      responses:
        '200':
          description: A JSON array of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized
    post:
      summary: Add a new transaction
      description: Adds a new transaction to the specified account.
      requestBody:
        description: Transaction object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transaction created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /transactions/{transactionId}:
    get:
      summary: Get details of a specific transaction
      description: Returns the details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID of the transaction to retrieve
      responses:
        '200':
          description: A transaction object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
    put:
      summary: Update an existing transaction
      description: Updates the details of an existing transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID of the transaction to update
      requestBody:
        description: Updated transaction object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transaction updated
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
    delete:
      summary: Delete a transaction
      description: Deletes a transaction by ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID of the transaction to delete
      responses:
        '204':
          description: Transaction deleted
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found

components:
  schemas:
    Transaction:
      type: object
      required:
        - accountId
        - amount
        - date
        - description
      properties:
        id:
          type: string
          description: Unique identifier for the transaction
        accountId:
          type: string
          description: ID of the account associated with the transaction
        amount:
          type: number
          format: float
          description: Amount of the transaction
        date:
          type: string
          format: date
          description: Date of the transaction
        description:
          type: string
          description: Description of the transaction
        category:
          type: string
          description: Category of the transaction
        notes:
          type: string
          description: Additional notes for the transaction
